<?php
// Generated by agent based on C:\Users\manis\OneDrive\Documents\MKTechPrep\AgenticAIPractice\php-hello-world\agents/../tasks/task-calc-sum.md
$acceptTwoInputs = true;$defaultNonNumToZero = true;$noInputFromUser = true;$addTwoNums = true;
$sum = 0;
if ($acceptTwoInputs) {
    $num1 = $_GET['num1'] ?? 0;
    $num2 = $_GET['num2'] ?? 0;

    // Step 1: check for missing inputs
    if($noInputFromUser && ($num1 === 0 && $num2 === 0)) {
        $sum = 0;
    }
    // Step 2: check for non-numeric inputs
    else if($defaultNonNumToZero && (!is_numeric($num1) || !is_numeric($num2))) {
        $sum = 0;
    }
    // Step 3: compute sum if both inputs are accepted
    else if ($addTwoNums) {
            $sum = $num1 + $num2;
    }
}
// Step 4: Output result
echo $sum;