<?php
// Strands-style multi-task PHP agent
// Reads a task SOP, validates answers, generates PHP code

// --- Task folder ---
$tasksFolder = __DIR__ . '/../tasks';
$allTasks = glob($tasksFolder . '/task-*.md');

// --- Select task ---
$taskFile = $argv[1] ?? null;

if (!$taskFile) {
    echo "Available tasks:\n";
    foreach ($allTasks as $i => $file) {
        echo ($i + 1) . ". " . basename($file) . "\n";
    }
    $choice = readline("Select a task by number: ");
    $index = intval($choice) - 1;
    if (!isset($allTasks[$index])) {
        echo "Invalid selection.\n";
        exit(1);
    }
    $taskFile = $allTasks[$index];
} else {
    $taskFile = __DIR__ . '/../' . ltrim($taskFile, '/');
    if (!file_exists($taskFile)) {
        echo "Task file not found: $taskFile\n";
        exit(1);
    }
}

// --- Read task content ---
$taskContent = file_get_contents($taskFile);

// --- Extract answers dynamically ---
$answers = [];
if (preg_match('/## Answers([\s\S]*)$/', $taskContent, $match)) {
    preg_match_all('/> (.+)/', $match[1], $matches);
    $answers = array_map('trim', $matches[1]);
}

// --- Count questions dynamically ---
$questionCount = preg_match_all('/\d+\.\s.*$/m', $taskContent);

// --- Validate answers ---
if (count($answers) < $questionCount) {
    echo "Incomplete answers.\nPlease answer all questions in the task file.\n";
    exit(0);
}

// --- Determine behavior from answers ---
$outputUpper = isset($answers[0]) && strtoupper($answers[0]) === 'YES';
$acceptInput = isset($answers[1]) && strtoupper($answers[1]) === 'YES';
// echo implode("\n", $answers) . "\n". $outputUpper . "\n" . $acceptInput . "\n";
// exit(0);


// --- Start building code string ---
$code = "<?php\n";
$code .= "// Generated by agent based on $taskFile\n";
$code .= "// to run this file on the browser- run /c/php/php.exe -S localhost:8000 on the terminal at /c/Users/manis/OneDrive/Documents/MKTechPrep/AgenticAIPractice/php-hello-world  Git Bash from vs code terminal. This will start a local server at localhost:8000. Then open the browser and go to localhost:8000/index.php?name=YourName to see the output, or if you run without the 'name' param, it will default to WORLD.\n\n";

// --- Generate PHP code based on answers ---
if ($acceptInput) {
    $code .= '$name = $_GET["name"] ?? "WORLD";' . "\n";
    $code .= 'echo ' . ($outputUpper ? 'strtoupper($name)' : '$name') . ";\n";
} else {
    $code .= 'echo ' . ($outputUpper ? '"HELLO WORLD"' : '"Hello World"') . ";\n";
}

// --- Write generated code to index.php in repo root ---
$repoRoot = realpath(__DIR__ . '/..');
file_put_contents($repoRoot . '/index.php', $code);

echo "Generated index.php from $taskFile\n";
