<?php
// Simple agent to read a task SOP and generate PHP code

$taskFile = $argv[1] ?? 'tasks/task-hello-world.md';
if (!file_exists($taskFile)) {
    echo "Task file not found: $taskFile\n";
    exit(1);
}

$taskContent = file_get_contents($taskFile);

// Parse the answers to the Questions section
preg_match_all('/> (.+)/', $taskContent, $matches);
$answers = $matches[1];

// --- clean up answers and define variables ---
$answers = array_map('trim', $answers);  // remove whitespace

/* validation block */
// --- VALIDATION: ensure Answers section exists ---
if (!str_contains($taskContent, '## Answers')) {
    echo "No Answers section found.\n";
    echo "Please answer the questions in the task file and re-run.\n";
    exit(0);
}

// Parse answers (already done earlier)
if (count($answers) < 3) {
    echo "Incomplete answers.\n";
    echo "Please answer all questions in the task file.\n";
    exit(0);
}

$outputUpper = (isset($answers[0]) && strtoupper($answers[0]) === 'YES') ? true : false;
$acceptInput = (isset($answers[2]) && strtoupper($answers[2]) === 'YES') ? true : false;

// --- start building the code string ---
$code = "<?php\n";
$code .= "// Generated by agent based on $taskFile\n";

// Generate output based on the answers
if ($acceptInput) {
    $code .= '$name = $_GET["name"] ?? "WORLD";' . "\n";
    $code .= 'echo ' . ($outputUpper ? 'strtoupper($name)' : '$name') . ";\n";
} else {
    $code .= 'echo ' . ($outputUpper ? '"HELLO WORLD"' : '"Hello World"') . ";\n";
}

// Write the generated code to index.php in repo root
$repoRoot = realpath(__DIR__ . '/..');
file_put_contents($repoRoot . '/index.php', $code);

echo "Generated index.php from $taskFile\n";
