<?php
// Strands-style multi-task PHP agent
// Reads a task SOP, validates answers, generates PHP code

// --- Task folder ---
$tasksFolder = __DIR__ . '/../tasks';
$allTasks = glob($tasksFolder . '/task-*.md');

// --- Select task ---
$taskFile = $argv[1] ?? null;

if (!$taskFile) {
    echo "Available tasks:\n";
    foreach ($allTasks as $i => $file) {
        echo ($i + 1) . ". " . basename($file) . "\n";
    }
    $choice = readline("Select a task by number: ");
    $index = intval($choice) - 1;
    if (!isset($allTasks[$index])) {
        echo "Invalid selection.\n";
        exit(1);
    }
    $taskFile = $allTasks[$index];
} else {
    $taskFile = __DIR__ . '/../' . ltrim($taskFile, '/');
    if (!file_exists($taskFile)) {
        echo "Task file not found: $taskFile\n";
        exit(1);
    }
}

// --- Read task content ---
$taskContent = file_get_contents($taskFile);
// echo $taskContent . "\n";
// exit(0);

// --- Extract answers dynamically ---
$answers = [];
if (preg_match('/## Answers([\s\S]*)$/', $taskContent, $match)) {
    preg_match_all('/> (.+)/', $match[1], $matches);
    $answers = array_map('trim', $matches[1]);
}
// echo implode("\n", $answers) . "\n";

// --- Count questions dynamically ---
$questionCount = preg_match_all('/\d+\.\s.*$/m', $taskContent);

// preg_match_all('/\d+\.\s(.+)$/m', $taskContent, $questionMatches);
// $questions = array_map('trim', $questionMatches[1]);
// echo "Questions:\n" . implode("\n", $questions) . "\n"; <- prints all questions

// --- Validate answers ---
if (count($answers) < $questionCount) {
    echo "Incomplete answers.\nPlease answer all questions in the task file.\n";
    exit(0);
}

// --- Determine behavior from answers ---
$acceptTwoInputs = isset($answers[0]) && strtoupper($answers[0]) === 'YES';
$defaultNonNumToZero = isset($answers[1]) && strtoupper($answers[1]) === 'YES';
$noInputFromUser = isset($answers[2]) && strtoupper($answers[2]) === 'YES';
$addTwoNums = isset($answers[3]) && strtoupper($answers[3]) === 'YES';


// --- Start building code string ---
$code = "<?php\n";
$code .= "// Generated by agent based on $taskFile\n";
$code .= "// to run this file on the browser- run /c/php/php.exe -S localhost:8000 on the terminal at /c/Users/manis/OneDrive/Documents/MKTechPrep/AgenticAIPractice/php-hello-world  Git Bash from vs code terminal. This will start a local server at localhost:8000. Then open the browser and go to http://localhost:8000/index.php?num1=2&num2=5 to see the output, or if you run without the num1=2&num2=5 params, it will default to 0.\n\n";

// --- Generate PHP code based on answers ---
$code .= ''. $acceptTwoInputs ? '$acceptTwoInputs = true;' : '$acceptTwoInputs = false;' . "\n";
$code .= ''. $defaultNonNumToZero ? '$defaultNonNumToZero = true;' : '$defaultNonNumToZero = false;' . "\n";
$code .= ''. $noInputFromUser ? '$noInputFromUser = true;' : '$noInputFromUser = false;' . "\n";
$code .= ''. $addTwoNums ? '$addTwoNums = true;' : '$addTwoNums = false;' . "\n   ";

$code .= '
$sum = 0;
if ($acceptTwoInputs) {
    $num1 = $_GET[\'num1\'] ?? 0;
    $num2 = $_GET[\'num2\'] ?? 0;

    // Step 1: check for missing inputs
    if($noInputFromUser && ($num1 === 0 && $num2 === 0)) {
        $sum = 0;
    }
    // Step 2: check for non-numeric inputs
    else if($defaultNonNumToZero && (!is_numeric($num1) || !is_numeric($num2))) {
        $sum = 0;
    }
    // Step 3: compute sum if both inputs are accepted
    else if ($addTwoNums) {
            $sum = $num1 + $num2;
    }
}
// Step 4: Output result
echo $sum;';
// echo $code . "\n";
// exit(0);

// --- Write generated code to index.php in repo root ---
$repoRoot = realpath(__DIR__ . '/..');
file_put_contents($repoRoot . '/index.php', $code);

echo "Generated index.php from $taskFile\n";
