<?php
// Simple agent to read a task SOP and generate PHP code

$taskFile = $argv[1] ?? 'tasks/task-hello-world.md';
if (!file_exists($taskFile)) {
    echo "Task file not found: $taskFile\n";
    exit(1);
}

$taskContent = file_get_contents($taskFile);

// Parse the answers to the Questions section
preg_match_all('/> (.+)/', $taskContent, $matches);
$answers = $matches[1];

// Determine behavior based on answers
$outputUpper = strtolower($answers[0] ?? 'yes') === 'yes';
$acceptInput = strtolower($answers[2] ?? 'no') === 'yes';

$code = "<?php\n";
$code .= "// Generated by agent based on $taskFile\n";

if ($acceptInput) {
    $code .= '$name = $_GET["name"] ?? "WORLD";' . "\n";
    $code .= 'echo ' . ($outputUpper ? 'strtoupper($name)' : '$name') . ";\n";
} else {
    $code .= 'echo ' . ($outputUpper ? '"HELLO WORLD"' : '"Hello World"') . ";\n";
}

file_put_contents('../index.php', $code);

echo "Generated index.php from $taskFile\n";
